export type ProposeActions = {
    OBJECTID: string
    subtype: number
    quantity: string
    jurisdiction: string
    mdp_osp_study_name: string
    year_of_study: number
    year_constructed: number
    status: string
    drainageway: string
    reach: string
    id: string
    unit: string
    unit_cost: number
    checked_by: string
    estimated_cost: number
    station_limits: string
    original_cost: number
    station_limits_us: string
    station_limits_ds: string
    current_cost: number
    mhfdmanager: string
    servicearea: string
    county: string
    problemid: number
    projectid: number
    type: string
    status2022: string
    component_id: string
    GlobalID: string
    created_user: string
    created_date: string
    last_edited_user: string
    last_edited_date: string
    component_type: string
    study_id: number
    original_cost_backup: number
}